version: '3'

services:
  chat_app:
    build:
      context: ./chat_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - chat_app

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
