version: '3'

services:
  chat_app:
    build:
      context: ./chat_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis

  translator_api:
    build:
      context: ./translator
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    command: sh -c "python manage.py runserver 0.0.0.0:7000"

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
